### ISSUE TITLE
Installing Java

### ISSUE THREAD

**Issue by KonstantinSelyuk** [KonstantinSelyuk/First-Android-Project#1]
So, dear colleagues,
 lets start out first android project.
The first task for you will be:
1) Please install Java Development Kid (Jdk) on your PC ( just Java) 
2) Check it in command line: print " java -version " and press ENTER, you must obtain something like:
     java version "1.7.0_51"
    Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
    Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)

3) Please write comment to this issue and paste the output of command " java -version " in your PC.

If you have any questions please write it in comments or directly contact me in skype.

**Comment by KonstantinSelyuk** [comment]
Please delete Java from your PC and try to install the new version from here ( http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html )
Choose this one : Java SE Development Kit 8u31 -   jdk-8u31-windows-x64.exe

**Comment by PashaSelyk** [comment]
I installed the java, but only for windows-x32.
In command prompt wrote the following: Microsoft Windows [Version 6.1.7601](c) Корпорация Майкрософт (Microsoft Corp.), 2009. Все права защищены.

C:\Users\Pashka>java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) Client VM (build 25.31-b07, mixed mode)

**Comment by PashaSelyk** [comment]
I installed the java, but only for windows-x32.
In command prompt wrote the following: Microsoft Windows [Version 6.1.7601](c) Корпорация Майкрософт (Microsoft Corp.), 2009. Все права защищены.

C:\Users\Pashka>java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) Client VM (build 25.31-b07, mixed mode)

**Comment by PashaSelyk** [comment]
I installed the java, but only for windows-x32.
In command prompt wrote the following: 

Microsoft Windows [Version 6.1.7601]
(c) Корпорация Майкрософт (Microsoft Corp.), 2009. Все права защищены.

C:\Users\Pashka>java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) Client VM (build 25.31-b07, mixed mode)

**Comment by KonstantinSelyuk** [comment]
ok, very good, but why did you choose java for windows-x32? 
Check your system type (My Computer-> right click of mouse -> properties)
For example I hava the next: 
  "System type: 64-bit Operation System"

**Comment by PashaSelyk** [comment]
On my computer installed Windows x32

11.02.2015, 15:24, "KonstantinSelyuk" notifications@github.com:

**Comment by PashaSelyk** [comment]
I customized Eclipse? i can greate first project "Hello World"

11.02.2015, 15:24, "KonstantinSelyuk" notifications@github.com:
